keys:
  - &admin_tydooo 85B0B835399023EB
  - &host_zoltraak age13d2pjc2jd54e5czgscpatrtu6dh7kycz08eger5vey6n98s2s5tsf59utr
  - &host_judradjim age166v46ym7gw72fkncca0k7q0u7x60yle2utkzw27apmr7rrylfccqmaypev
creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
      - pgp:
          - *admin_tydooo
        age:
          - *host_zoltraak
          - *host_judradjim
  - path_regex: users/[^/]+/secrets.ya?ml$
    key_groups:
      - pgp:
          - *admin_tydooo
        age:
          - *host_zoltraak
          - *host_judradjim
  - path_regex: hosts/zoltraak/secrets.ya?ml$
    key_groups:
      - pgp:
          - *admin_tydooo
        age:
          - *host_zoltraak
  - path_regex: hosts/judradjim/secrets.ya?ml$
    key_groups:
      - pgp:
          - *admin_tydooo
        age:
          - *host_judradjim
